<BusesList>:
    container: container

    MDBoxLayout:
        orientation: 'vertical'

        MDToolbar:
            title: "Prakapenka - Lab3 (Buses List)"
            use_overflow: True
            right_action_items: [["arrow-left-bold", lambda x: root.go_back()]]
            elevation: 10

        MDBoxLayout:
            orientation: 'vertical'

            ScrollView:

                MDList:
                    id: container

